### ISSUE TITLE
[script.module.future] Matrix update Python to 3.8.5 causes exception

### ISSUE THREAD

**Issue by rschupp** [xbmc/repo-scripts#1672]
Note: that problem isn't specific to Andoid.

`splitattr` is gone from `urllib.request` in Python 3.8

```
2020-08-19 17:07:30.563 T:31293   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'splitattr' from 'urllib.request' (/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/service.py", line 1, in <module>
                                                       from resources.lib.scheduler import BackupScheduler
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/scheduler.py", line 8, in <module>
                                                       from resources.lib.backup import XbmcBackup
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 10, in <module>
                                                       from . vfs import XBMCFileSystem, DropboxFileSystem, ZipFileSystem
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 11, in <module>
                                                       from . authorizers import DropboxAuthorizer
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/authorizers.py", line 4, in <module>
                                                       import resources.lib.tinyurl as tinyurl
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/tinyurl.py", line 3, in <module>
                                                       from future.moves.urllib.request import urlopen
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.future/libs/future/moves/urllib/request.py", line 9, in <module>
                                                       from urllib.request import (getproxies,
                                                   ImportError: cannot import name 'splitattr' from 'urllib.request' (/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py)
                                                   -->End of Python script error report<--
```

_Originally posted by @CiNcH83 in https://github.com/xbmc/xbmc/pull/18240#issuecomment-676491578_

**Comment by ronie** [comment]
fixed by https://github.com/xbmc/repo-scripts/pull/1675
