### ISSUE TITLE
MultiWeather: Weather Error since 0.0.9 update

### ISSUE THREAD

**Issue by darkenvy** [xbmc/repo-scripts#2225]
I get a generic error every time I open Kodi. After checking the logs, I get the following output from MultiWeather:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 0
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/weather.multi/default.py", line 5, in <module>
                                                       weather.MAIN(mode=sys.argv[1])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/weather.multi/lib/weather.py", line 35, in __init__
                                                       self.get_forecast(location, locationid, locationlat, locationlon, ycookie, ycrumb)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/weather.multi/lib/weather.py", line 157, in get_forecast
                                                       yahoo.Weather.get_weather(data, loc, locid)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/weather.multi/lib/providers/yahoo.py", line 8, in get_weather
                                                       data = response['weathers'][0]
                                                   KeyError: 0
                                                   -->End of Python script error report<--
```

**Comment by lrusak** [comment]
I think it's known, https://forum.kodi.tv/showthread.php?tid=352028&pid=3086785#pid3086785
